name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  selenium_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0  # Replace with your Python version
        
      - name: Install Dependencies
        run: |
         pip install selenium
  # Add any other necessary dependencies with "pip install" as well


      - name: Run Selenium Tests
        run: python ntest.py
