name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  selenium_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0  # Replace with your Python version

      - name: Install Dependencies
        run: |
          pip install selenium

      - name: Set up ChromeDriver
        run: |
          # Download and install ChromeDriver (adjust the version as needed)
          CHROMEDRIVER_VERSION="119.0.6045.105"  # Replace with the desired ChromeDriver version
          wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Run Selenium Tests
        run: python prog.py
