name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  selenium_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0  # Replace with your Python version

      - name: Install Dependencies
        run: |
          pip install selenium

      - name: Set up ChromeDriver
        run: |
    # Specify the ChromeDriver version (e.g., xx.x.x)
           $CHROMEDRIVER_VERSION = "119.0.6045.105"
    
    # Create a directory for ChromeDriver (you can change the path as needed)
           New-Item -ItemType Directory -Force -Path C:\chromedriver

    # Download ChromeDriver
    Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_win32.zip" -OutFile C:\chromedriver\chromedriver.zip

    # Extract the downloaded archive
    Expand-Archive -Path C:\chromedriver\chromedriver.zip -DestinationPath C:\chromedriver

    # Add the ChromeDriver directory to the system PATH
    [System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\chromedriver", [System.EnvironmentVariableTarget]::Machine)


      - name: Run Selenium Tests
        run: python prog.py
