name: Trigger Repo B Workflow

on:
  workflow_run:
    workflows: ["Your Workflow Name in Repo A"]
    types:
      - completed

jobs:
  trigger_repo_b:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repo B Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_REPO_B }}" \
            https://api.github.com/repos/owner/repo-b/dispatches \
            -d '{"event_type": "start-cicd"}'
